name: 'user'
port: 8021

user_srv:
  host: '127.0.0.1'
  port: 50051
  name: 'user-server'

jwt:
  key: '5$!UEmvB#nRB@Iwab#Sy!zofKEOGLRtE'

sms:
  key: 'LTAI4FzGkwzJyrKfCex9kpP1'
  secrect: 'r5aWSxybxkuT4ROcwpRqqusXtcwxt5'
  expire: 300

redis:
  host: '192.168.1.3'
  port: 6379

consul:
  host: '192.168.1.3'
  port: 8500
